#!/usr/bin/env node
/**
 * ADR-0017 token build.
 *
 * Reads tokens.json (the single source of truth) and deterministically emits:
 *   css/tokens.css — custom properties on `:root` (light) + `[data-theme="dark"]` overrides
 *   src/tokens.ts  — typed TS constants mirroring the same data
 *
 * Zero dependencies. Output is byte-identical across runs (idempotent).
 * Run: pnpm --filter @onemark/design-tokens build
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const tokens = JSON.parse(readFileSync(join(PKG_ROOT, 'tokens.json'), 'utf8'));

const GENERATED =
  'Generated by src/build.mjs from tokens.json — DO NOT EDIT BY HAND.\n' +
  '  Source of truth: packages/design-tokens/tokens.json (ADR-0017).\n' +
  '  Regenerate:      pnpm --filter @onemark/design-tokens build';

/* ------------------------------------------------------------------ */
/* CSS                                                                 */
/* ------------------------------------------------------------------ */

const SEMANTIC_NAMES = ['success', 'warning', 'danger', 'info', 'important'];
const SEMANTIC_ROLES = ['bg', 'border', 'text'];

/** theme.light.background -> --om-bg, etc. (short semantic aliases) */
const ROLE_VAR = {
  background: '--om-bg',
  surface: '--om-surface',
  'surface-raised': '--om-surface-raised',
  border: '--om-border',
  'border-strong': '--om-border-strong',
  text: '--om-text',
  'text-muted': '--om-text-muted',
  'text-subtle': '--om-text-subtle',
  primary: '--om-primary',
  'primary-hover': '--om-primary-hover',
  'primary-active': '--om-primary-active',
  'on-primary': '--om-on-primary',
  'focus-ring': '--om-focus-ring',
};

/** Custom properties that switch per theme. */
function themeScopedLines(theme) {
  const lines = [];
  for (const name of SEMANTIC_NAMES) {
    for (const role of SEMANTIC_ROLES) {
      lines.push(`  --om-${name}-${role}: ${tokens.semantic[name][theme][role]};`);
    }
  }
  for (const [key, cssVar] of Object.entries(ROLE_VAR)) {
    lines.push(`  ${cssVar}: ${tokens.theme[theme][key]};`);
  }
  for (const [k, v] of Object.entries(tokens.shadow[theme])) {
    lines.push(`  --om-shadow-${k}: ${v};`);
  }
  lines.push(`  --om-backdrop: ${tokens.backdrop[theme]};`);
  lines.push(`  --om-color-scheme: ${tokens.colorScheme[theme]};`);
  for (const [k, v] of Object.entries(tokens.syntax[theme])) {
    lines.push(`  --om-syntax-${k}: ${v};`);
  }
  return lines;
}

/** Theme-independent custom properties (shared by both themes). */
function sharedLines() {
  const lines = [];
  for (const [step, hex] of Object.entries(tokens.color.primary)) lines.push(`  --om-color-primary-${step}: ${hex};`);
  for (const [step, hex] of Object.entries(tokens.color.gray)) lines.push(`  --om-color-gray-${step}: ${hex};`);
  for (const [k, v] of Object.entries(tokens.space)) lines.push(`  --om-space-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --om-radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.borderWidth)) lines.push(`  --om-border-width-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.control)) lines.push(`  --om-control-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.focusRing)) lines.push(`  --om-focus-ring-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.opacity)) lines.push(`  --om-opacity-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.motion.duration)) lines.push(`  --om-duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.motion.easing)) lines.push(`  --om-ease-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.motion.transition)) lines.push(`  --om-transition-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.typography.fontFamily)) lines.push(`  --om-font-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.typography.fontSize)) lines.push(`  --om-font-size-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.typography.lineHeight)) lines.push(`  --om-line-height-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.typography.letterSpacing)) lines.push(`  --om-letter-spacing-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.typography.fontWeight)) lines.push(`  --om-weight-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.zIndex)) lines.push(`  --om-z-${k}: ${v};`);
  return lines;
}

const rootLines = sharedLines().concat(themeScopedLines('light'));
const darkLines = themeScopedLines('dark');

const css = `/*
 * ${GENERATED}
 *
 * Theme contract: light values live on :root; the app flips themes by setting
 * data-theme="dark" on <html> (see apps/web/src/theme.ts). Because the dark
 * block is a plain attribute selector, any subtree can also opt in locally by
 * setting data-theme="dark" on a container element (useful for previews).
 */

:root {
  color-scheme: light;

${rootLines.join('\n')}
}

[data-theme="dark"] {
  color-scheme: dark;

${darkLines.join('\n')}
}
`;

/* ------------------------------------------------------------------ */
/* TypeScript                                                          */
/* ------------------------------------------------------------------ */

const SECTION_NAMES = [
  'color',
  'semantic',
  'theme',
  'shadow',
  'backdrop',
  'colorScheme',
  'syntax',
  'space',
  'radius',
  'borderWidth',
  'control',
  'focusRing',
  'opacity',
  'motion',
  'typography',
  'zIndex',
];

const ts = `/**
 * ${GENERATED}
 */

${SECTION_NAMES.map((name) => `export const ${name} = ${JSON.stringify(tokens[name], null, 2)} as const;`).join('\n\n')}

export const tokens = {
  ${SECTION_NAMES.join(',\n  ')},
} as const;

export type Tokens = typeof tokens;
export type ThemeName = keyof typeof theme;
export type SemanticName = keyof typeof semantic;
export type CssCustomProperty = \`--om-\${string}\`;
`;

/* ------------------------------------------------------------------ */
/* Emit                                                                */
/* ------------------------------------------------------------------ */

mkdirSync(join(PKG_ROOT, 'css'), { recursive: true });
writeFileSync(join(PKG_ROOT, 'css', 'tokens.css'), css);
writeFileSync(join(PKG_ROOT, 'src', 'tokens.ts'), ts);

const decls = css.match(/^\s*--om-[\w-]+:/gm) ?? [];
const unique = new Set(decls.map((d) => d.trim().replace(/:$/, '')));
console.log(`[design-tokens] wrote css/tokens.css (${decls.length} custom-property declarations, ${unique.size} unique)`);
console.log('[design-tokens] wrote src/tokens.ts');
