/**
 * Generated by src/build.mjs from tokens.json — DO NOT EDIT BY HAND.
  Source of truth: packages/design-tokens/tokens.json (ADR-0017).
  Regenerate:      pnpm --filter @onemark/design-tokens build
 */

export const color = {
  "primary": {
    "50": "#fdf5f3",
    "100": "#fbe8e2",
    "200": "#f6cfc4",
    "300": "#efa892",
    "400": "#e57c5f",
    "500": "#c8412d",
    "600": "#b03622",
    "700": "#8f2b1b",
    "800": "#6f2216",
    "900": "#551c14",
    "950": "#33100b"
  },
  "gray": {
    "0": "#ffffff",
    "50": "#f6f8fa",
    "100": "#eaeef2",
    "200": "#d8dee4",
    "300": "#b1bac4",
    "400": "#8c959f",
    "500": "#6e7781",
    "600": "#57606a",
    "700": "#424a53",
    "800": "#32383f",
    "900": "#24292f",
    "1000": "#000000"
  }
} as const;

export const semantic = {
  "success": {
    "light": {
      "bg": "#e9f7ee",
      "border": "#4ac26b",
      "text": "#1a7f37"
    },
    "dark": {
      "bg": "#12311f",
      "border": "#2ea043",
      "text": "#4ec96a"
    }
  },
  "warning": {
    "light": {
      "bg": "#fff8c5",
      "border": "#d4a72c",
      "text": "#9a6700"
    },
    "dark": {
      "bg": "#2a2008",
      "border": "#bb8009",
      "text": "#d29922"
    }
  },
  "danger": {
    "light": {
      "bg": "#ffebe9",
      "border": "#ff8182",
      "text": "#cf222e"
    },
    "dark": {
      "bg": "#321419",
      "border": "#e5534b",
      "text": "#f85149"
    }
  },
  "info": {
    "light": {
      "bg": "#ddf4ff",
      "border": "#54aeff",
      "text": "#0969da"
    },
    "dark": {
      "bg": "#12233c",
      "border": "#316dca",
      "text": "#4493f8"
    }
  },
  "important": {
    "light": {
      "bg": "#faf5ff",
      "border": "#c297ff",
      "text": "#8250df"
    },
    "dark": {
      "bg": "#201b33",
      "border": "#8957e5",
      "text": "#ab7df8"
    }
  }
} as const;

export const theme = {
  "light": {
    "background": "#ffffff",
    "surface": "#f6f8fa",
    "surface-raised": "#ffffff",
    "border": "#d0d7de",
    "border-strong": "#afb8c1",
    "text": "#1f2328",
    "text-muted": "#59636e",
    "text-subtle": "#656d76",
    "primary": "#c8412d",
    "primary-hover": "#b03622",
    "primary-active": "#8f2b1b",
    "on-primary": "#ffffff",
    "focus-ring": "#c8412d"
  },
  "dark": {
    "background": "#0d1117",
    "surface": "#161b22",
    "surface-raised": "#1f2630",
    "border": "#30363d",
    "border-strong": "#444c56",
    "text": "#e6edf3",
    "text-muted": "#9198a1",
    "text-subtle": "#7d8590",
    "primary": "#e57c5f",
    "primary-hover": "#f08a6b",
    "primary-active": "#d96a4c",
    "on-primary": "#0d1117",
    "focus-ring": "#e57c5f"
  }
} as const;

export const shadow = {
  "light": {
    "sm": "0 1px 2px rgba(31, 35, 40, 0.06)",
    "md": "0 1px 2px rgba(31, 35, 40, 0.06), 0 4px 12px rgba(31, 35, 40, 0.1)",
    "lg": "0 4px 12px rgba(31, 35, 40, 0.1), 0 16px 40px rgba(31, 35, 40, 0.14)"
  },
  "dark": {
    "sm": "0 1px 2px rgba(1, 4, 9, 0.35)",
    "md": "0 1px 2px rgba(1, 4, 9, 0.35), 0 4px 12px rgba(1, 4, 9, 0.45)",
    "lg": "0 4px 12px rgba(1, 4, 9, 0.45), 0 16px 40px rgba(1, 4, 9, 0.55)"
  }
} as const;

export const backdrop = {
  "light": "rgba(31, 35, 40, 0.5)",
  "dark": "rgba(1, 4, 9, 0.7)"
} as const;

export const colorScheme = {
  "light": "light",
  "dark": "dark"
} as const;

export const syntax = {
  "light": {
    "keyword": "#cf222e",
    "string": "#0a3069",
    "comment": "#6e7781",
    "number": "#0550ae",
    "function": "#8250df",
    "tag": "#116329",
    "attr": "#953800",
    "punctuation": "#24292f"
  },
  "dark": {
    "keyword": "#ff7b72",
    "string": "#a5d6ff",
    "comment": "#8b949e",
    "number": "#79c0ff",
    "function": "#d2a8ff",
    "tag": "#7ee787",
    "attr": "#ffa657",
    "punctuation": "#e6edf3"
  }
} as const;

export const space = {
  "0": "0px",
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "5": "20px",
  "6": "24px",
  "7": "28px",
  "8": "32px",
  "9": "36px",
  "10": "40px",
  "11": "44px",
  "12": "48px",
  "13": "52px",
  "14": "56px",
  "15": "60px",
  "16": "64px",
  "17": "68px",
  "18": "72px",
  "19": "76px",
  "20": "80px",
  "21": "84px",
  "22": "88px",
  "23": "92px",
  "24": "96px"
} as const;

export const radius = {
  "sm": "6px",
  "md": "10px",
  "lg": "14px",
  "xl": "20px",
  "full": "9999px"
} as const;

export const borderWidth = {
  "thin": "1px",
  "thick": "2px"
} as const;

export const control = {
  "sm": "28px",
  "md": "32px",
  "lg": "40px"
} as const;

export const focusRing = {
  "width": "2px",
  "offset": "2px"
} as const;

export const opacity = {
  "disabled": 0.55,
  "hover": 0.8
} as const;

export const motion = {
  "duration": {
    "instant": "100ms",
    "fast": "150ms",
    "base": "250ms",
    "slow": "400ms"
  },
  "easing": {
    "standard": "cubic-bezier(0.2, 0, 0, 1)",
    "decelerate": "cubic-bezier(0, 0, 0.2, 1)",
    "accelerate": "cubic-bezier(0.4, 0, 1, 1)",
    "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
    "linear": "linear"
  },
  "transition": {
    "colors": "color 150ms cubic-bezier(0.2, 0, 0, 1), background-color 150ms cubic-bezier(0.2, 0, 0, 1), border-color 150ms cubic-bezier(0.2, 0, 0, 1), fill 150ms cubic-bezier(0.2, 0, 0, 1), stroke 150ms cubic-bezier(0.2, 0, 0, 1)",
    "opacity": "opacity 150ms cubic-bezier(0.2, 0, 0, 1)",
    "transform": "transform 250ms cubic-bezier(0.2, 0, 0, 1)",
    "shadow": "box-shadow 250ms cubic-bezier(0.2, 0, 0, 1)"
  }
} as const;

export const typography = {
  "fontFamily": {
    "ui": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Noto Sans\", Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\"",
    "mono": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, Consolas, \"Liberation Mono\", monospace"
  },
  "fontSize": {
    "xs": "12px",
    "sm": "13px",
    "base": "14px",
    "md": "16px",
    "lg": "20px",
    "xl": "24px",
    "2xl": "32px",
    "3xl": "40px",
    "4xl": "56px"
  },
  "lineHeight": {
    "none": "1",
    "xs": "16px",
    "sm": "20px",
    "base": "20px",
    "md": "24px",
    "lg": "28px",
    "xl": "32px",
    "2xl": "40px",
    "3xl": "48px",
    "4xl": "64px"
  },
  "letterSpacing": {
    "tight": "-0.02em",
    "normal": "0em",
    "wide": "0.08em"
  },
  "fontWeight": {
    "regular": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700
  }
} as const;

export const zIndex = {
  "base": 0,
  "raised": 1,
  "dropdown": 100,
  "sticky": 200,
  "overlay": 300,
  "modal": 400,
  "toast": 500,
  "tooltip": 600
} as const;

export const tokens = {
  color,
  semantic,
  theme,
  shadow,
  backdrop,
  colorScheme,
  syntax,
  space,
  radius,
  borderWidth,
  control,
  focusRing,
  opacity,
  motion,
  typography,
  zIndex,
} as const;

export type Tokens = typeof tokens;
export type ThemeName = keyof typeof theme;
export type SemanticName = keyof typeof semantic;
export type CssCustomProperty = `--om-${string}`;
