import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalize } from './normalize.mjs';
import { loadNodeEngine } from '@onemark/engine/node';
import { renderToSafeHtml } from '@onemark/renderer';
import { JSDOM } from 'jsdom';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const id = process.argv[2], idx = Number(process.argv[3]);
const engine = await loadNodeEngine();
const source = readFileSync(join(root, 'corpus', `${id}.md`), 'utf8');
const ast = await engine.parse(source, { dialect: 'gfm', extensions: { tables: true, strikethrough: true, autolink: true, taskList: true, footnotes: true, alerts: true, math: true, frontmatter: true } });
const dom = new JSDOM('');
const ours = renderToSafeHtml(ast, { window: dom.window });
const a = normalize(ours), b = normalize(readFileSync(join(root, 'golden', `${id}.html`), 'utf8'));
const body = a.children[0].children[1].children[0];
const bodyT = b.children[0].children[1].children[0];
console.log('OURS body['+idx+']:', JSON.stringify(body.children[idx]).slice(0, 900));
console.log('THEIRS body['+idx+']:', JSON.stringify(bodyT.children[idx]).slice(0, 900));
