// @vitest-environment jsdom
/**
 * Task 1.6 — KaTeX math, bundled fonts.
 *
 * Pipeline shape (ADR-0014 lesson applied): the renderer emits a inert
 * `<span class="onemark-math">` placeholder carrying the escaped LaTeX; the
 * sanitiser passes it through untouched; `renderToSafeHtml` then hydrates the
 * placeholders with locally-generated KaTeX markup *after* sanitisation.
 *
 * Rationale: KaTeX's correct layout requires inline styles and MathML, both of
 * which the allowlist rightly forbids for *document* content. Math generated by
 * our own bundled KaTeX with `trust: false` is not document content — it is
 * program output, generated after the security boundary, from LaTeX the
 * sanitiser has already seen and passed as inert text.
 */

import { beforeAll, describe, expect, it } from 'vitest';
import { loadNodeEngine, GFM_OPTIONS, type MarkdownEngine } from '@onemark/engine';
import { renderToSafeHtml, renderToUnsafeHtml } from '../src/index.js';

let engine: MarkdownEngine;

beforeAll(async () => {
  engine = await loadNodeEngine();
});

describe('math typesetting (task 1.6)', () => {
  it('hydrates inline math into KaTeX markup', async () => {
    const ast = await engine.parse('Euler: $e^{i\\pi} + 1 = 0$ done\n', GFM_OPTIONS);
    const html = renderToSafeHtml(ast);
    expect(html).toContain('class="katex"');
    expect(html).toContain('e^{i\\pi}');
  });

  it('hydrates block math in display mode', async () => {
    const ast = await engine.parse('$$\nx^2 + y^2 = z^2\n$$\n', GFM_OPTIONS);
    const html = renderToSafeHtml(ast);
    expect(html).toMatch(/katex-display/);
  });

  it('keeps the placeholder inert when the unsafe path is used', async () => {
    const ast = await engine.parse('Value $x^2$ here\n', GFM_OPTIONS);
    const html = renderToUnsafeHtml(ast);
    expect(html).toContain('onemark-math');
    expect(html).not.toContain('class="katex"');
  });

  it('never emits a network reference (M2)', async () => {
    const ast = await engine.parse('$$\\frac{a}{b}$$\n', GFM_OPTIONS);
    const html = renderToSafeHtml(ast);
    expect(html).not.toMatch(/(src|href)="https?:/);
    expect(html).not.toMatch(/@import|<link/);
  });

  it('renders hostile LaTeX without script execution vectors', async () => {
    const ast = await engine.parse('$\\href{javascript:alert(1)}{x}$\n', GFM_OPTIONS);
    const html = renderToSafeHtml(ast);
    // trust:false makes KaTeX refuse the \href; the string may survive only as
    // inert text (MathML annotation), never as a live attribute.
    expect(html).not.toMatch(/href\s*=\s*["']?\s*javascript:/i);
    expect(html).not.toContain('<script');
    expect(html).toMatch(/#cc0000/); // KaTeX's error colour marks the refusal
  });
});
