// @vitest-environment jsdom
/**
 * **ADR-0015 layer 3: screenshot diff for the vendored GitHub CSS.**
 *
 * Chromium renders the reference fixture with each vendored theme; the
 * `.markdown-body` element is screenshotted and pixel-diffed against a
 * committed baseline. Baselines are generated by the first run — delete them
 * to re-baseline, and treat any re-baseline as a fidelity decision (ADR-0015).
 *
 * One engine only (Chromium): font raster differs across engines, so a
 * cross-engine pixel gate would be noise. Layers 1–2 in theme.test.ts carry
 * the cross-theme guarantees; this layer catches visual regressions that
 * declarations alone hide.
 *
 * Not part of the default suite. Run with `pnpm --filter @onemark/renderer test:visual`.
 */

import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { chromium, type Browser, type Page } from 'playwright';
import pixelmatch from 'pixelmatch';
import { PNG } from 'pngjs';

import { loadNodeEngine } from '@onemark/engine/node';
import { GFM_OPTIONS } from '@onemark/engine';
import { renderToSafeHtml } from '../src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const cssDir = join(here, '..', 'css');
const baselineDir = join(here, '__screenshots__', 'theme');
const fixtureMd = readFileSync(join(here, 'fixtures', 'reference-document.md'), 'utf8');

const THEMES = ['github-light.css', 'github-dark.css'] as const;

let browser: Browser;
let page: Page;

beforeAll(async () => {
  browser = await chromium.launch();
  page = await browser.newPage({ viewport: { width: 900, height: 800 }, deviceScaleFactor: 1 });
});

afterAll(async () => {
  await browser?.close();
});

describe('theme screenshots vs committed baselines (ADR-0015 layer 3)', () => {
  for (const theme of THEMES) {
    it(`${theme} matches its baseline`, async () => {
      const engine = await loadNodeEngine();
      const ast = await engine.parse(fixtureMd, GFM_OPTIONS);
      const html = renderToSafeHtml(ast);

      const doc = `<!doctype html><html><head><meta charset="utf-8"><style>
        body { margin: 16px; }
        ${readFileSync(join(cssDir, theme), 'utf8')}
      </style></head><body><div class="markdown-body">${html}</div></body></html>`;

      await page.setContent(doc, { waitUntil: 'networkidle' });
      const el = page.locator('.markdown-body');
      const shot: Buffer = await el.screenshot();

      mkdirSync(baselineDir, { recursive: true });
      const baselinePath = join(baselineDir, `${theme}.baseline.png`);
      if (!existsSync(baselinePath)) {
        writeBaseline(baselinePath, shot);
        console.warn(`baseline generated (commit it): ${baselinePath}`);
        return;
      }

      const baseline = PNG.sync.read(readFileSync(baselinePath));
      const actual = PNG.sync.read(shot);
      expect(actual.width).toBe(baseline.width);
      expect(actual.height).toBe(baseline.height);

      const diff = new PNG({ width: actual.width, height: actual.height });
      const changed = pixelmatch(
        actual.data, baseline.data, diff.data,
        actual.width, actual.height, { threshold: 0.1 },
      );
      const ratio = changed / (actual.width * actual.height);
      if (ratio > 0.001) {
        writeBaseline(join(baselineDir, `${theme}.diff.png`), PNG.sync.write(diff));
      }
      expect(ratio, `${theme}: ${(ratio * 100).toFixed(3)}% pixels differ`).toBeLessThanOrEqual(0.001);
    });
  }
});

function writeBaseline(path: string, data: Buffer) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, data);
}
