//! OneMark desktop shell — M2 (task 2.2 onward).
//!
//! The shell hosts the apps/web build and exposes the **native** engine
//! behind the same contract the WASM build serves on the web: `parse_markdown`
//! takes markdown source and returns the AST JSON exactly as
//! `crates/onemark-engine` emits it (byte-identical to the WASM build per
//! NFR-6 — asserted by this crate's determinism test against the shared
//! contract fixtures).
//!
//! Real M2 lands here next: FolderStorage via the dialog/fs plugins
//! (security-scoped bookmarks), native menus and `.md` file associations,
//! file watching.

use onemark_engine::{parse_to_json, ParseOptions};

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {} — from the OneMark shell", name)
}

/// Native parse (task 2.2): same engine, same options, same AST JSON shape
/// the web worker returns. `GFM` options are fixed at the boundary, matching
/// the web worker's lock.
#[tauri::command]
fn parse_markdown(source: &str) -> Result<serde_json::Value, String> {
    let json = parse_to_json(source, &ParseOptions::gfm());
    serde_json::from_str(&json).map_err(|e| format!("engine emitted invalid JSON: {e}"))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet, parse_markdown])
        .run(tauri::generate_context!())
        .expect("error while running OneMark shell");
}

#[cfg(test)]
mod determinism {
    //! Task 2.7 groundwork: the shell's native engine must produce AST JSON
    //! byte-identical to what the TypeScript contract suite asserts against.
    //! The fixtures are generated by `crates/onemark-engine`'s dump example —
    //! the same files `packages/engine/test/contract.test.ts` checks.

    use super::parse_to_json;
    use onemark_engine::ParseOptions;
    use std::fs;
    use std::path::PathBuf;

    /// Mirrors `crates/onemark-engine/examples/dump_fixtures.rs`. Kept in sync
    /// deliberately: a divergence here is exactly what the test exists to catch.
    const FIXTURES: &[(&str, &str)] = &[
        ("heading", "# hello\n"),
        ("gfm_table", "| a | b |\n|:--|--:|\n| 1 | 2 |\n"),
        ("task_list", "- [x] done\n- [ ] todo\n"),
        ("alert", "> [!WARNING]\n> careful\n"),
        ("math", "$x^2$\n\n$$y = 1$$\n"),
        ("frontmatter", "---\ntitle: hi\n---\n\n# body\n"),
        ("code_block", "```rust\nfn main() {}\n```\n"),
        ("footnote", "text[^a]\n\n[^a]: note\n"),
    ];

    fn fixtures_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../packages/engine/test/fixtures")
    }

    #[test]
    fn native_ast_is_structurally_identical_to_the_contract_fixtures() {
        let dir = fixtures_dir();
        for (name, source) in FIXTURES {
            let path = dir.join(format!("{name}.json"));
            let raw = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("fixture {} missing: {e}", path.display()));
            let expected: serde_json::Value =
                serde_json::from_str(&raw).expect("fixture is valid JSON");
            let actual: serde_json::Value =
                serde_json::from_str(&parse_to_json(source, &ParseOptions::gfm()))
                    .expect("engine emitted valid JSON");
            assert_eq!(
                actual, expected,
                "native engine AST diverged from the contract fixture for {name}"
            );
        }
    }

    #[test]
    fn every_dumped_fixture_has_a_determinism_case() {
        // The mirror must not silently rot: the dump example's manifest lists
        // every fixture it emitted; each must appear in the mirror above.
        let manifest_path = fixtures_dir().join("manifest.json");
        let raw = fs::read_to_string(&manifest_path).expect("fixture manifest readable");
        let manifest: serde_json::Value = serde_json::from_str(&raw).expect("manifest is JSON");
        let names: Vec<String> = manifest
            .as_array()
            .expect("manifest is an array")
            .iter()
            .filter_map(|e| e.get("name").and_then(|n| n.as_str()).map(String::from))
            .collect();
        let mirrored: Vec<String> = FIXTURES.iter().map(|(n, _)| n.to_string()).collect();
        let mut a = names.clone();
        let mut b = mirrored.clone();
        a.sort();
        b.sort();
        assert_eq!(a, b, "fixture set changed: update the shell's determinism mirror");
    }
}
